package entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * FOOD ENTITY CLASS - Indian and Gujarati Vegetarian Menu
 *
 * PURPOSE:
 * This class represents a menu item in our Indian vegetarian restaurant.
 * It stores details about each dish including name, category, price,
 * description, and availability status.
 *
 * WHY THIS CLASS EXISTS:
 * The restaurant needs to display its menu to customers. This class holds
 * all the information about each dish - from a crispy Samosa starter to
 * a complete Gujarati Thali meal.
 *
 * MENU CATEGORIES (8 total):
 * 1. Starters         - Samosa, Dhokla, Khandvi, Paneer Tikka, Onion Bhaji
 * 2. Gujarati Special - Thali, Undhiyu, Dal Dhokli, Handvo, Thepla
 * 3. North Indian     - Paneer Butter Masala, Dal Makhani, Chole Bhature
 * 4. South Indian     - Masala Dosa, Idli Sambar, Medu Vada, Uttapam
 * 5. Breads           - Naan, Roti, Paratha, Puri
 * 6. Rice and Biryani - Vegetable Biryani, Paneer Biryani, Jeera Rice
 * 7. Desserts         - Gulab Jamun, Jalebi, Rasmalai, Gajar Halwa
 * 8. Beverages        - Masala Chai, Mango Lassi, Jaljeera
 *
 * @author Group 10 - Online Restaurant Project
 * @version 1.0
 * @since 2026
 */
public class Food implements Serializable {

    // ===================== PRIVATE FIELDS =====================

    /**
     * MENU ITEM ID: Unique number for each dish in our restaurant.
     * Auto-generated by database when a new item is added to menu.
     * Example: 1 = Samosa, 5 = Gujarati Thali, 39 = Gulab Jamun
     */
    private int foodId;

    /**
     * DISH NAME: The name customers see on the menu.
     * Should be descriptive and appetizing!
     * Examples: "Samosa", "Gujarati Thali", "Masala Dosa"
     */
    private String name;

    /**
     * FOOD CATEGORY: Groups similar dishes together.
     * Used for filtering the menu display.
     * Valid values: Starters, Gujarati Special, North Indian, etc.
     */
    private String category;

    /**
     * DISH DESCRIPTION: Detailed explanation of the food item.
     * Helps customers understand what they are ordering.
     * Example: "Crispy pastry filled with spiced potatoes and peas"
     */
    private String description;

    /**
     * PRICE: Cost of the dish in British Pounds.
     * Using BigDecimal for accurate monetary calculations.
     * Never use double or float for prices - rounding errors!
     */
    private BigDecimal price;

    /**
     * IMAGE URL: Filename of the food photograph.
     * Stored in web/resources/images/ folder.
     * Example: "samosa.jpg", "gujaratithali.jpg"
     */
    private String imageUrl;

    /**
     * AVAILABILITY: Is this dish currently being served?
     * true  = Available (shown normally on menu)
     * false = Sold out (greyed out on menu)
     * Helps manage inventory when items run out.
     */
    private boolean isAvailable;

    /**
     * DATE ADDED: When this dish was added to the menu.
     * Useful for tracking new additions and seasonal items.
     * Automatically set by database on insert.
     */
    private Date createdAt;

    // ===================== CONSTRUCTORS =====================

    /**
     * DEFAULT CONSTRUCTOR - Required for JavaBeans specification.
     * JSF framework needs this to create instances when binding to XHTML.
     * Sets default availability to true (available for ordering).
     */
    public Food() {
        // By default, all menu items are available
        // Admin can change this if item is sold out
        this.isAvailable = true;
    }

    /**
     * PARAMETERIZED CONSTRUCTOR
     * Creates a new menu item with all details.
     * Used when admin adds a new dish to the restaurant menu.
     *
     * @param name        - Name of the dish (e.g., "Masala Dosa")
     * @param category    - Category (e.g., "South Indian")
     * @param description - Detailed description for customers
     * @param price       - Price in GBP (e.g., 8.99)
     * @param imageUrl    - Filename of food photograph (e.g., "masaladosa.jpg")
     */
    public Food(String name, String category, String description,
                BigDecimal price, String imageUrl) {
        this.name = name;
        this.category = category;
        this.description = description;
        this.price = price;
        this.imageUrl = imageUrl;
        // New items are always available by default
        this.isAvailable = true;
    }

    // ===================== GETTERS AND SETTERS =====================
    // These provide controlled access to private fields.
    // Following JavaBean naming convention required by JSF framework.

    /**
     * Gets the unique menu item ID.
     * @return foodId from database
     */
    public int getFoodId() {
        return foodId;
    }

    /**
     * Sets the menu item ID (called by DAO when retrieving records).
     * @param foodId - unique identifier from database
     */
    public void setFoodId(int foodId) {
        this.foodId = foodId;
    }

    /**
     * Gets the dish name as shown on menu.
     * @return name of food item
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the dish name.
     * @param name - name to display on menu
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the category for menu filtering.
     * @return category string (e.g., "Starters", "Gujarati Special")
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the category for grouping dishes.
     * @param category - must match one of 8 predefined categories
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * Gets the dish description for customers.
     * @return description text
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the dish description.
     * @param description - detailed description for customers
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Gets the price of the dish.
     * @return price as BigDecimal (for accurate monetary math)
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * Sets the price of the dish.
     * @param price - cost in GBP
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * Gets the image filename for the dish photo.
     * Used in XHTML pages to display food images.
     * Example: "samosa.jpg"
     * @return imageUrl filename string
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * Sets the image filename.
     * @param imageUrl - filename of image in resources/images/ folder
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * Gets just the image filename for use in XHTML img tags.
     * This method is used in menu.xhtml as #{item.imageName}
     * Handles cases where imageUrl might contain a full path.
     *
     * EXAMPLE USAGE IN JSF:
     * src="#{request.contextPath}/resources/images/#{item.imageName}"
     *
     * @return just the filename (e.g., "samosa.jpg")
     */
    public String getImageName() {
        if (imageUrl == null || imageUrl.trim().isEmpty()) {
            // Return default image if no image is set
            return "samosa.jpg";
        }
        // If imageUrl contains a full path, extract just the filename
        if (imageUrl.contains("/")) {
            return imageUrl.substring(imageUrl.lastIndexOf("/") + 1);
        }
        return imageUrl;
    }

    /**
     * Checks if dish is currently available for ordering.
     * @return true if available, false if sold out
     */
    public boolean isIsAvailable() {
        return isAvailable;
    }

    /**
     * Sets the availability status of the dish.
     * @param isAvailable - true = available, false = sold out
     */
    public void setIsAvailable(boolean isAvailable) {
        this.isAvailable = isAvailable;
    }

    /**
     * Gets the date this item was added to the menu.
     * @return creation timestamp
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets the creation date (usually set automatically by database).
     * @param createdAt - timestamp of menu addition
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    // ===================== HELPER METHODS =====================

    /**
     * FORMATTING: Converts price to display format with currency symbol.
     * Used in XHTML pages to show prices like "£12.99" instead of "12.99"
     *
     * EXAMPLE USAGE IN JSF:
     * value="#{food.formattedPrice}"
     *
     * @return price string with £ symbol (e.g., "£8.99")
     */
    public String getFormattedPrice() {
        if (price == null) {
            return "£0.00";
        }
        return String.format("£%.2f", price);
    }

    /**
     * DEBUGGING: String representation of food item.
     * Used for logging and troubleshooting.
     * 
     * @return formatted string with food details
     */
    @Override
    public String toString() {
        return "Food{" +
                "foodId=" + foodId +
                ", name='" + name + '\'' +
                ", category='" + category + '\'' +
                ", price=" + price +
                ", isAvailable=" + isAvailable +
                '}';
    }
}