package entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
 * ORDER ENTITY CLASS - Customer Order Header
 * 
 * PURPOSE:
 * This class represents a complete customer order - the "header" information.
 * Each order has one header (this class) and multiple order items.
 * 
 * WHY THIS CLASS EXISTS:
 * When a customer checks out, we need to store:
 * - Who ordered (userId)
 * - When they ordered (orderDate)
 * - How much they paid (totalAmount)
 * - Where to deliver (deliveryAddress)
 * - Current status (status - pending, confirmed, etc.)
 * 
 * ORDER LIFECYCLE:
 * 1. PENDING    - Order placed, waiting for restaurant confirmation
 * 2. CONFIRMED  - Restaurant accepted the order
 * 3. PREPARING  - Kitchen is cooking the food
 * 4. DELIVERED  - Food has been delivered to customer
 * 5. CANCELLED  - Order was cancelled (by customer or restaurant)
 * 
 * @author Group 10 - Online Restaurant Project
 * @version 1.0
 * @since 2024
 * 
 */
public class Order implements Serializable {
    
    // PRIVATE FIELDS
    
    /*
     * ORDER ID: Unique number for each order.
     * Auto-generated by database.
     * Customer sees this as "Order #123" on confirmation page.
     */
    private int orderId;
    
    /*
     * CUSTOMER ID: Who placed this order?
     * Foreign key to users table.
     * Used to show order history for specific customer.
     */
    private int userId;
    
    /*
     * ORDER TIMESTAMP: When did customer place the order?
     * Set automatically to current date/time when order is created.
     * Used for tracking and delivery time estimation.
     */
    private Date orderDate;
    
    /*
     * TOTAL AMOUNT: How much did customer pay?
     * Sum of all order items (price × quantity).
     * Includes tax (already in price for UK).
     */
    private BigDecimal totalAmount;
    
    /*
     * ORDER STATUS: Current stage in fulfillment process.
     * Updated by restaurant staff (or automatically).
     * Customer can track their order status.
     */
    private String status;
    
    /*
     * DELIVERY ADDRESS: Where to deliver the food?
     * Copied from user's profile at checkout.
     * Customer can provide different address if needed.
     */
    private String deliveryAddress;
    
    /*
     * PAYMENT METHOD: How did customer pay?
     * Options: credit_card, debit_card, cash, online
     * Used for payment processing and receipts.
     */
    private String paymentMethod;
    
    // TRANSIENT FIELDS (Not stored in database)
    // These are for display purposes only - not saved to database
    
    /*
     * ORDER ITEMS LIST: All dishes in this order.
     * Not stored directly - populated by OrderDAO using JOIN query.
     * Used on order confirmation and order history pages.
     */
    private List<OrderItem> orderItems;
    
    /*
     * CUSTOMER OBJECT: User who placed the order.
     * Not stored directly - populated when needed.
     * Used to show customer details on admin pages.
     */
    private User user;
    
    // ORDER STATUS CONSTANTS
    // These are the only valid status values
    // Using constants prevents typos and ensures consistency
    
    /**
     * Status: Order received but not yet confirmed by restaurant
     */
    public static final String STATUS_PENDING = "pending";
    
    /**
     * Status: Restaurant has accepted the order
     */
    public static final String STATUS_CONFIRMED = "confirmed";
    
    /**
     * Status: Kitchen is currently preparing the food
     */
    public static final String STATUS_PREPARING = "preparing";
    
    /**
     * Status: Food has been delivered to customer
     */
    public static final String STATUS_DELIVERED = "delivered";
    
    /**
     * Status: Order was cancelled (cannot be changed after this)
     */
    public static final String STATUS_CANCELLED = "cancelled";
    
    // CONSTRUCTORS
    
    /**
     * DEFAULT CONSTRUCTOR
     * Required for JavaBeans specification.
     * Sets default status to "pending" and order date to current time.
     */
    public Order() {
        this.status = STATUS_PENDING;
        this.orderDate = new Date(); // Current date and time
    }
    
    /**
     * PARAMETERIZED CONSTRUCTOR
     * Creates a new order with essential information.
     * Called during checkout process.
     * 
     * @param userId          - Customer placing the order
     * @param totalAmount     - Total cost of order
     * @param deliveryAddress - Where to deliver
     * @param paymentMethod   - How customer is paying
     */
    public Order(int userId, BigDecimal totalAmount, String deliveryAddress, String paymentMethod) {
        this.userId = userId;
        this.totalAmount = totalAmount;
        this.deliveryAddress = deliveryAddress;
        this.paymentMethod = paymentMethod;
        this.status = STATUS_PENDING;      // New orders start as pending
        this.orderDate = new Date();       // Timestamp of order placement
    }
    
    // GETTERS AND SETTERS
    
    public int getOrderId() {
        return orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    
    public int getUserId() {
        return userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    
    public Date getOrderDate() {
        return orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }
    
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }
    
    public String getStatus() {
        return status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    public String getDeliveryAddress() {
        return deliveryAddress;
    }
    
    public void setDeliveryAddress(String deliveryAddress) {
        this.deliveryAddress = deliveryAddress;
    }
    
    public String getPaymentMethod() {
        return paymentMethod;
    }
    
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }
    
    public List<OrderItem> getOrderItems() {
        return orderItems;
    }
    
    public void setOrderItems(List<OrderItem> orderItems) {
        this.orderItems = orderItems;
    }
    
    public User getUser() {
        return user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    
    // HELPER METHODS
    
    /**
     * FORMAT TOTAL: Returns total amount with £ symbol.
     * Used on checkout and order confirmation pages.
     * 
     * @return formatted total (e.g., "£42.97")
     */
    public String getFormattedTotal() {
        return "£" + (totalAmount != null ? totalAmount.toString() : "0.00");
    }
    
    /**
     * FORMAT DATE: Returns order date in readable format.
     * Converts from database timestamp to UK date format.
     * Example: "15/01/2024 18:30"
     * 
     * @return formatted date string (DD/MM/YYYY HH:MM)
     */
    public String getFormattedOrderDate() {
        if (orderDate != null) {
            // UK date format: day/month/year hour:minute
            return new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm").format(orderDate);
        }
        return ""; // Return empty string if date is null (shouldn't happen)
    }
    
    /**
     * STATUS CHECK: Is order still pending?
     * Used to show "Cancel Order" button on customer dashboard.
     * 
     * @return true if status is "pending"
     */
    public boolean isPending() {
        return STATUS_PENDING.equals(status);
    }
    
    /**
     * STATUS CHECK: Has order been delivered?
     * Used to show "Reorder" button on order history page.
     * 
     * @return true if status is "delivered"
     */
    public boolean isDelivered() {
        return STATUS_DELIVERED.equals(status);
    }
    
    /**
     * STATUS CHECK: Was order cancelled?
     * Used to show different message on order history.
     * 
     * @return true if status is "cancelled"
     */
    public boolean isCancelled() {
        return STATUS_CANCELLED.equals(status);
    }
    
    /**
     * CSS CLASS FOR STATUS BADGE: Returns appropriate CSS class.
     * Used to color-code order status on admin and customer pages.
     * 
     * Color scheme:
     * - pending   → yellow (waiting)
     * - confirmed → blue (accepted)
     * - preparing → purple (in progress)
     * - delivered → green (completed)
     * - cancelled → red (cancelled)
     * 
     * @return CSS class name for styling
     */
    public String getStatusBadgeClass() {
        switch (status) {
            case STATUS_PENDING:
                return "badge-warning";    // Yellow - waiting
            case STATUS_CONFIRMED:
                return "badge-info";       // Blue - confirmed
            case STATUS_PREPARING:
                return "badge-primary";    // Purple - cooking
            case STATUS_DELIVERED:
                return "badge-success";    // Green - delivered
            case STATUS_CANCELLED:
                return "badge-danger";     // Red - cancelled
            default:
                return "badge-secondary";  // Grey - unknown status
        }
    }
    
    /**
     * DEBUGGING: String representation of order.
     * Used for logging and troubleshooting.
     * 
     * @return formatted string with order details
     */
    @Override
    public String toString() {
        return "Order{" +
                "orderId=" + orderId +
                ", userId=" + userId +
                ", totalAmount=" + totalAmount +
                ", status='" + status + '\'' +
                '}';
    }
}