package entities;

import java.io.Serializable;
import java.util.Date;

/**
 * User Entity Class - Online Restaurant Website (Indian & Gujarati Cuisine)
 * 
 * PURPOSE:
 * This class represents a customer or administrator in the restaurant system.
 * It maps directly to the 'users' table in the Apache Derby database.
 * 
 * WHY THIS CLASS EXISTS:
 * In a restaurant ordering system, we need to track who is ordering food.
 * This class stores customer profiles including their delivery address,
 * which is essential for home delivery of Gujarati and Indian meals.
 * 
 * BUSINESS RULES:
 * - Each user must have a unique username (no two customers can share login)
 * - Each user must have a unique email (for order confirmations)
 * - Role can be 'customer' (regular user) or 'admin' (restaurant manager)
 * - Default role is 'customer' when a new user registers
 * 
 * @author Group 10 - Online Restaurant Project
 * @version 1.0
 * @since 2026
 */
public class User implements Serializable {

    // ===================== FIELDS =====================
    
    /**
     * UNIQUE IDENTIFIER: Each user gets a unique number when they register.
     * This is automatically generated by the database (auto-increment).
     * Think of this as the user's account ID in our restaurant system.
     */
    private int userID;

    /**
     * LOGIN CREDENTIAL: The username is what customers type to log in.
     * Must be unique - no two customers can have the same username.
     * Example: "priya_patel" or "raj_sharma"
     */
    private String userName;

    /**
     * CONTACT INFORMATION: Email is used for two purposes:
     * 1. Login alternative (customer can use email instead of userName)
     * 2. Sending order confirmation receipts after purchase
     * Must be unique in the system.
     */
    private String email;

    /**
     * SECURITY: Password stored in database.
     * Note: In production, this should be hashed using PasswordUtil.java
     * Never store plain text passwords in real applications!
     */
    private String password;

    /**
     * PERSONAL INFORMATION: Customer's full name.
     * This appears on order receipts and delivery labels.
     * Example: "Priya Patel" or "Raj Sharma"
     */
    private String fullName;

    /**
     * CONTACT NUMBER: Used by delivery person to call if needed.
     * Format: 10-11 digits (UK mobile)
     */
    private String phone;

    /**
     * DELIVERY LOCATION: Where to deliver the food.
     * This is crucial for our restaurant delivery service.
     * Example: "15 Linthrope Road, HA0 2HJ"
     */
    private String address;

    /**
     * ACCESS LEVEL: Determines what pages the user can access.
     * - "customer": Can order food, view history, leave reviews
     * - "admin": Can add/edit menu items, manage orders, view all users
     * Default is "customer" for new registrations.
     */
    private String role;

    /**
     * TIMESTAMP: Records when the customer joined our restaurant.
     * Useful for tracking loyal customers and sending birthday offers.
     * Automatically set by database when record is inserted.
     */
    private Date createdAt;

    // ===================== CONSTRUCTORS =====================

    /**
     * Default Constructor - Required for JavaBeans specification.
     * JSF framework needs a no-argument constructor to create instances
     * when binding to XHTML pages.
     * Sets default role to "customer" - most users are regular customers.
     */
    public User() {
        // Every new user starts as a regular customer
        // Admin privileges must be granted manually in database
        this.role = "customer";
    }

    /**
     * Parameterized Constructor - Creates user with basic information.
     * Used when retrieving user data from database or creating new user.
     *
     * @param userID   - Unique identifier from database
     * @param userName - Login name chosen by customer
     * @param email    - Customer's email address for communication
     * @param fullName - Customer's real name for delivery labels
     * @param phone    - Contact number for delivery coordination
     * @param address  - Delivery address for food delivery
     */
    public User(int userID, String userName, String email, String fullName,
            String phone, String address) {
        this.userID = userID;
        this.userName = userName;
        this.email = email;
        this.fullName = fullName;
        this.phone = phone;
        this.address = address;
        this.role = "customer";
    }

    // ===================== GETTERS AND SETTERS =====================
    // These methods provide controlled access to private fields.
    // Following JavaBean naming convention required by JSF framework.

    /**
     * Gets the user's unique ID number.
     * @return userID from database
     */
    public int getUserID() {
        return userID;
    }

    /**
     * Sets the user's ID (called by DAO when retrieving records).
     * @param userID - the unique identifier to set
     */
    public void setUserID(int userID) {
        this.userID = userID;
    }

    /**
     * Gets userName for login display.
     * @return userName string
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the userName.
     * @param userName - desired login name
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * Gets the email address for communication.
     * @return email string
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the email address.
     * @param email - customer's email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Gets the password.
     * @return password string
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the password.
     * @param password - customer's chosen password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Gets customer's full name for delivery labels and welcome message.
     * 
     * FIXED: Previously this method was throwing UnsupportedOperationException
     * because NetBeans auto-generated it without implementation.
     * Now correctly returns the fullName field value.
     * 
     * @return fullName string (e.g. "Priya Patel")
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the full name.
     * @param fullName - Customer's real name
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * Gets contact phone number.
     * @return phone number string
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the phone number.
     * @param phone - contact number
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Gets delivery address.
     * @return address string
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the delivery address.
     * @param address - where to deliver food
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * Gets user role (customer or admin).
     * @return role string
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets user role (only admin should change this).
     * @param role - "customer" or "admin"
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * Gets account creation timestamp.
     * @return date when user registered
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets the creation timestamp (usually set by database).
     * @param createdAt - registration date/time
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    // ===================== HELPER METHODS =====================

    /**
     * Checks if user has administrator privileges.
     * Used in XHTML pages to conditionally show admin menu items.
     * 
     * EXAMPLE USAGE IN JSF:
     * rendered="#{loginBean.currentUser.admin}"
     * 
     * @return true if user role is "admin", false for regular customers
     */
    public boolean isAdmin() {
        return "admin".equalsIgnoreCase(role);
    }

    /**
     * Checks if user is a regular customer.
     * Used to conditionally show customer-only features.
     * 
     * @return true if user role is "customer", false for admins
     */
    public boolean isCustomer() {
        return "customer".equalsIgnoreCase(role);
    }

    /**
     * Returns string representation of user for debugging/logging.
     * NOTE: Password is deliberately NOT included for security reasons!
     * 
     * @return formatted string with user details
     */
    @Override
    public String toString() {
        return "User{" +
                "userID=" + userID +
                ", username='" + userName + '\'' +
                ", email='" + email + '\'' +
                ", fullName='" + fullName + '\'' +
                ", role='" + role + '\'' +
                '}';
        // Password deliberately omitted from toString() for security
    }
}